export PATH=$HOME/.local/bin:$PATH

# java
export PATH=$HOME/.sdkman/candidates/java/current/bin/:$PATH
export JAVA_HOME=$HOME/.sdkman/candidates/java/current/
export ANDROID_HOME="$HOME/.local/android_sdk/"
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/emulator

export PATH=$(go env GOPATH)/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export EDITOR=nvim
export TIMELUA_STATUS_FILE="$HOME/.timelua"

# Aliases

alias t="tmux attach -t 0"
alias lg="lazygit"

alias notes="cd ~/notes/2025/; nvim ."

alias cnvim="cd $HOME/.config/nvim"
alias opens="cd $HOME/dev/open_source"
alias proj="cd $HOME/dev/projects"
alias kbase="cd $HOME/dev/kbase"
alias ctx="cd $HOME/.config/tmux"
alias dev="cd $HOME/dev"

# MACOS Specific
if [[ $OS_TYPE == "darwin*" ]]; then
    alias love="/Applications/love.app/Contents/MacOS/love"
    alias droid="open -a /Applications/Android\ Studio.app/"
    alias intellij="open -a /Applications/IntelliJ\ IDEA\ CE.app/"
    alias killDerived="rm -rf ~/Library/Developer/Xcode/DerivedData/*"
    alias killSpmCache="rm -rf ~/Library/Caches/org.swift.swiftpm; rm -rf ~/Library/org.swift.swiftpm"
fi

# Linux Specific
if [[ $OS_TYPE == "linux*" ]]; then
    export CS_HOME="$HOME/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Counter-Strike Global Offensive/game/csgo/"
fi

if [[ -d ~/dev/open_source/emsdk/ ]]; then
    export EMSDK_QUIET=1
    source ~/dev/open_source/emsdk/emsdk_env.sh
fi
